FROM spcleth/mignificient:base

ADD mignificient /source
RUN apt-get install -y gdb valgrind
RUN mkdir build && cd build && pybind11_DIR=/usr/local/lib/python3.8/dist-packages/pybind11 /cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug ../source/ && make -j16

