FROM spcleth/mignificient:base

# put it in the main one
RUN apt-get update && apt-get install -y --no-install-recommends libjsoncpp1 libjsoncpp-dev uuid-dev
ADD mignificient /source
#RUN apt-get install -y gdb valgrind
#RUN mkdir build && cd build && pybind11_DIR=/usr/local/lib/python3.8/dist-packages/pybind11 /cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug ../source/ && make -j16
RUN mkdir build && cd build && pybind11_DIR=/usr/local/lib/python3.8/dist-packages/pybind11 /cmake/bin/cmake -DCMAKE_BUILD_TYPE=Release ../source/ && make -j16

