FROM spcleth/mignificient:base-pytorch

RUN pip install --no-deps torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 && pip install pillow

ADD mignificient /source
RUN apt-get install -y gdb valgrind
RUN mkdir build && cd build && pybind11_DIR=/usr/local/lib/python3.8/dist-packages/pybind11 /cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug ../source/ && make -j16

RUN groupadd -g 1000 mcopik && useradd mcopik -u 1000 -g 1000 -m -s /bin/bash
